name: isp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain
    - openai
    - faiss-cpu
    - python-dotenv
    - tensorflow
    - numpy>=1.24
    - pandas>=2.0
    - pillow
    - matplotlib
    - langchain-openai
    - langchain-community
    - langchain-core
    - langchain-huggingface
    - scikit-learn
    - tqdm
    - hydra-core
    - sentence-transformers
    - kneed
    - umap-learn
    - seaborn
    - omegaconf
    - tensorflow
    - tf-keras
    - python-dotenv
    - ollama
    - langchain-ollama
    - anthropic
    - tabulate
